export const heads: string[] = [
    "cool",
    "smart",
    "cute",
    "weird",
    "lonely",
    "bored",
    "eating",
    "sleeping",
    "fast",
    "quick",
    "doing 10 pushups",
    "reading 10 books",
    "hungry",
    "tweeting",
    "annoying",
    "fierce",
    "crazy",
    "funny",
    "awkward",
    "brave",
    "human",
    "a jelly bean",
    "a BINGO!",
    "a captain",
    "real",
    "a myth",
    "everywhere",
    "good",
    "lazy loading",
    "punctual",
    "late again, sorry!",
    "unemployed",
    "dancing",
    "watching tv",
    "reading",
    "working",
    "coding 👨‍💻",
    "producing",
    "a writer",
    "rock solid",
    "vocal",
    "alive",
    "using his time wisely",
    "praying",
    "calm",
    "ready",
    "excited",
    "happy",
    "in love",
    "driving",
    "talking",
    "stupid",
    "clean",
    "going bald",
    "lost",
    "here",
    "not here",
    "nowhere",
    "at home, chillin",
    "sitting",
    "snoring",
    "creative",
    "talented",
    "caring",
    "careful",
    "da illest",
    "indian",
    "afraid",
    "young",
    "my friend",
    "indecisive",
    "scary",
    "😂🤣😂",
    "🤩🤩🤩",
    "😴🥱😔",
    "😵🤪🥴",
    "🤠🤠🤠",
    "🥳😁😝",
    "😎😎😎",
    "🤓🤓🤓",
    "🙈🐒🙈",
    "playing",
    "🎮🎮🎮",
    "🃏🃏🃏",
    "wrong",
    "right",
    "👀👀👀",
    "👨‍💻👨‍💻👨‍💻",
    "🦸‍♂️👨‍🎤🦹‍♂️",
    "🤹‍♂️🤹‍♂️🤹‍♂️",
    "trying his best",
    "🧘‍♂️🧘‍♂️🧘‍♂️",
    "🏃‍♂️🤸‍♂️🕺",
    "🤙🤙🤙",
    "big yeet",
    "100 emoji",
    "movin",
    "groovin",
    "movin/groovin",
    "big chillin",
    "a menace",
    "strange",
    "crazy",
    "everywhere",
    "in a desert, chillin",
    "laughing",
    "a bit harsh",
    "a bit blunt",
    "usually right...",
    "the man",
    "flaming hot",
    "looking for jobs",
    "capable of more",
    "not here rn sorry!",
    "almost there",
    "smarter than most (some)",
    "a wizard",
    "working",
    "in love with lama",
    "bouta cry ngl",
    "thinking of carnage...",
    "wise",
    "playing games",
    "taking too long",
    "picking up the pieces",
    "synchronous",
    "asynchronous",
    "cookin",
    "dancin",
    "feeding turtles",
    "doing jumping jacks",
    "fly",
    "meek",
    "mindful",
    "enduring a lame psyop",
    "grateful",
    "a provider",
    "putting his family first",
    "tired of games",
    "a bonehead",
    "happy!",
    "a good item to have",
    "gonna be a star ⭐",
    "praying for you",
    "praying for peace",
    "huffin and puffin",
    "inspiring the cool kids",
    "angering the lame kids",
    "an open source joke",
    "plagiarizing ur thoughts",
    "scared of big bugs",
    "scared of little bugs",
    "da king udda castle",
    "hopeful",
    "nervous",
    "learning new frameworks",
    "investigating the CIA",
    "collecting evidence",
    "doing his taxes",
    "just kidding! lol!",
    "tellin it like it is",
    "tired of games",
    "dreaming of a better day",
    "working to change the world",
    "inspiring the ghosts",
    "detecting robots",
    "drinking columbian coffee",
    "setting his phone to vibrate",
    "letting his ringtone ring",
    "doing stuff",
    "trustworthy",
    "eating a filet-o-fish",
    "bored",
    "satisfied",
    "building a new thing",
    "writing down his emotions",
    "playing solitaire",
    "playing idleon",
    "really strong",
    "running",
    "dragging on",
    "moving on",
    "thinking 🤔",
    "boop beep 🤖",
    "a AI (always important)",
    "kung fu fighting",
    "riding a scooter",
    "on a plane",
    "on a boat",
    "watching Loki 🍿",
    "daydreaming again...",
    "snoozin and losin",
    "cruisin for a bruisin",
    "dazed and confused",
    "steady",
    "cold, brrrr 🥶",
    "scribbling",
    "sitting in the corner lol",
    "OOO (out of office)",
    "not resisting",
    "prank calling 911 lol",
    "disrupting the disruptors",
    "breaking down walls",
    "building up walls",
    "paranoid af",
    "sexy af",
    "funny, hahaha",
    "rolling his eyes",
    "in bed, crying 😭",
    "afraid of heights",
    "afraid of money",
    "gaslighting you",
    "not botherin no one man",
    "real stoked to be here",
    "surfing 🌊",
    "picking up the trash",
    "doing his taxes",
    "a fraud",
    "a phony",
    "a ghost in a shell",
    "a magician 🪄",
    "dotting his eyes",
    "painting abstract stuff",
    "eating ice cream",
    "fighting wasps",
    "boxing kangaroos 🥊🦘",
    "eatin good",
    "pragmatic af",
    "a fine lad",
    "swell as a bell",
    "a true pioneer",
    "a living legend",
    "in the trees, ah!",
    "tackling the umpire",
    "savin it for later",
    "waiting...patiently...",
    "bouta sneeze...achoo!",
    "over it",
    "old 👴",
    "young 👶",
    "pain resistant",
    "undefeated",
    "a master of disguise",
    "fighting shadows",
    "befriending shadows",
    "praying for Palestine",
    "begging for salvation",
    "yearning for truth",
    "a real human bean",
    "cruel sometimes",
    "a joke",
    "damn good 👍",
    "a jeen YUHS",
    "struggling",
    "kicking arse 🦵",
    "worried about u",
    "very nice",
    "...???...!!!",
    "doing it right",
    "patiently waiting",
    "surfing 🌊 🏄",
    "feelin himself",
    "feelin that energy",
    "writing 10 books",
    "makin it look ez",
    "spam mail",
    "junk mail",
    "livin in da future",
    "makin a mess",
    "above it",
    "useless",
    "worthless",
    "burying this treasure!",
    "tanking",
    "PRINTING 💰",
    "cooked 🍳",
    "cracked",
    "courageous!",
    "superficial",
    "livin on the edge",
    "dogs",
    "DOGS",
    "moving to pluto",
    "holding on",
    "lighting the torches",
    "stealing the vapes",
    "doing taxes again",
    "saying it",
    "asking stupid questions",
    "seeing stars",
    "hearing sirens",
    "a dumpster fire",
    "times square",
    "picking up shit",
    "a plunger",
    "on it",
    "dancing",
    "woo! alright!",
    "unsustainable",
    "sustainable",
    "renewable",
    "non-renewable",
    "tenured",
    "pirating movies",
    "teaching birds about bees",
    "found, homeward bound",
    "in last place",
    "drifting in space",
    "don't care",
    "who cares"
];
