export const heads: string[] = [
    "cool",
    "smart",
    "cute",
    "weird",
    "lonely",
    "bored",
    "eating",
    "sleeping",
    "fast",
    "hungry",
    "tweeting",
    "annoying",
    "fierce",
    "crazy",
    "funny",
    "awkward",
    "brave",
    "human",
    "a captain",
    "real",
    "fake",
    "everywhere",
    "good",
    "lazy",
    "distraught",
    "punctual",
    "late",
    "employed",
    "singing",
    "dancing",
    "watching tv",
    "reading",
    "working",
    "coding",
    "producing",
    "a writer",
    "fat",
    "vocal",
    "out of shape",
    "dying",
    "alive",
    "wasting time",
    "making money",
    "praying",
    "listening",
    "calm",
    "ready",
    "excited",
    "happy",
    "in love",
    "driving",
    "talking",
    "stupid",
    "clean",
    "going bald",
    "lost",
    "here",
    "not here",
    "nowhere",
    "dull",
    "bologne",
    "at home",
    "sitting",
    "snoring",
    "creative",
    "talented",
    "caring",
    "careful",
    "ill",
    "indian",
    "afraid",
    "young",
    "my friend",
    "indecisive",
    "scary",
    "😂🤣😂",
    "🤩🤩🤩",
    "😴🥱😔",
    "😵🤪🥴",
    "🤠🤠🤠",
    "🥳😁😝",
    "😎😎😎",
    "🤓🤓🤓",
    "🙈🐒🙈",
    "playing",
    "🎮🎮🎮",
    "🃏🃏🃏",
    "wrong",
    "right",
    "👀👀👀",
    "👨‍💻👨‍💻👨‍💻",
    "🦸‍♂️👨‍🎤🦹‍♂️",
    "🤹‍♂️🤹‍♂️🤹‍♂️",
    "working out",
    "trying his best",
    "🧘‍♂️🧘‍♂️🧘‍♂️",
    "🏃‍♂️🤸‍♂️🕺",
    "🤙🤙🤙",
    "big yeet",
    "100 emoji",
    "movin",
    "groovin",
    "movin/groovin",
    "big chillin",
    "a menace",
    "strange",
    "crazy",
    "everywhere",
    "lost",
    "laughing"
];