export const heads: string[] = [
    "cool",
    "smart",
    "cute",
    "weird",
    "lonely",
    "bored",
    "eating",
    "sleeping",
    "fast",
    "quick",
    "doing 10 pushups",
    "reading 10 books",
    "hungry",
    "tweeting",
    "annoying",
    "fierce",
    "crazy",
    "funny",
    "awkward",
    "brave",
    "human",
    "a jelly bean",
    "a BINGO!",
    "a captain",
    "real",
    "a myth",
    "everywhere",
    "good",
    "lazy loading",
    "punctual",
    "late again, sorry!",
    "unemployed",
    "dancing",
    "watching tv",
    "reading",
    "working",
    "coding 👨‍💻",
    "producing",
    "a writer",
    "rock solid",
    "vocal",
    "alive",
    "using his time wisely",
    "praying",
    "calm",
    "ready",
    "excited",
    "happy",
    "in love",
    "driving",
    "talking",
    "stupid",
    "clean",
    "going bald",
    "lost",
    "here",
    "not here",
    "nowhere",
    "at home, chillin",
    "sitting",
    "snoring",
    "creative",
    "talented",
    "caring",
    "careful",
    "da illest",
    "indian",
    "afraid",
    "young",
    "my friend",
    "indecisive",
    "scary",
    "😂🤣😂",
    "🤩🤩🤩",
    "😴🥱😔",
    "😵🤪🥴",
    "🤠🤠🤠",
    "🥳😁😝",
    "😎😎😎",
    "🤓🤓🤓",
    "🙈🐒🙈",
    "playing",
    "🎮🎮🎮",
    "🃏🃏🃏",
    "wrong",
    "right",
    "👀👀👀",
    "👨‍💻👨‍💻👨‍💻",
    "🦸‍♂️👨‍🎤🦹‍♂️",
    "🤹‍♂️🤹‍♂️🤹‍♂️",
    "trying his best",
    "🧘‍♂️🧘‍♂️🧘‍♂️",
    "🏃‍♂️🤸‍♂️🕺",
    "🤙🤙🤙",
    "big yeet",
    "100 emoji",
    "movin",
    "groovin",
    "movin/groovin",
    "big chillin",
    "a menace",
    "strange",
    "crazy",
    "everywhere",
    "in a desert, chillin",
    "laughing",
    "a bit harsh",
    "a bit blunt",
    "usually right...",
    "the man",
    "flaming hot",
    "looking for jobs",
    "capable of more",
    "not here rn sorry!",
    "almost there",
    "smarter than most (some)",
    "a wizard",
    "working",
    "in love with lama",
    "bouta cry ngl",
    "thinking of carnage...",
    "wise",
    "playing games",
    "taking too long",
    "picking up the pieces",
    "synchronous",
    "asynchronous",
    "cookin",
    "dancin",
    "feeding turtles",
    "doing jumping jacks",
    "fly",
    "meek",
    "mindful",
    "enduring a lame psyop",
    "grateful",
    "a provider",
    "putting his family first",
    "tired of games",
    "a bonehead",
    "happy!",
    "a good item to have",
    "gonna be a star ⭐",
    "praying for you",
    "praying for peace",
    "huffin and puffin",
    "inspiring the cool kids",
    "angering the lame kids",
    "an open source joke",
    "plagiarizing ur thoughts",
    "scared of big bugs",
    "scared of little bugs",
    "da king udda castle",
    "hopeful",
    "nervous",
    "learning new frameworks",
    "investigating the CIA",
    "collecting evidence",
    "doing his taxes",
    "just kidding! lol!",
    "tellin it like it is",
    "tired of games",
    "dreaming of a better day",
    "working to change the world",
    "inspiring the ghosts",
    "detecting robots",
    "drinking columbian coffee",
    "setting his phone to vibrate",
    "letting his ringtone ring",
    "doing stuff",
    "trustworthy",
    "eating a filet-o-fish"
];
